name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 14 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "yjdqw@126.com"
          git config --local user.name "zds6668"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "Make Program Every Day!"
          git push
